apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: mcp-external-processor
  namespace: mcp-gateway
spec:
  configPatches:
    - applyTo: CLUSTER
      patch:
        operation: ADD
        value:
          connect_timeout: 1s
          http2_protocol_options: {}
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: mcp-ext-proc-cluster
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: mcp-ext-proc-filter.mcp-gateway.svc.cluster.local
                          port_value: 9001
          name: mcp-ext-proc-cluster
          type: STRICT_DNS
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: INSERT_FIRST
        value:
          name: envoy.filters.http.ext_proc
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor
            async_mode: false
            grpc_service:
              envoy_grpc:
                cluster_name: mcp-ext-proc-cluster
            processing_mode:
              request_body_mode: BUFFERED_PARTIAL
              request_header_mode: SEND
              response_body_mode: NONE
              response_header_mode: SKIP
            request_attributes:
              - x-mcp-tools
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: mcp-server-everything
