kind: Deployment
apiVersion: apps/v1
metadata:
  name: mcp-gateway
  namespace: mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-gateway
    spec:
      containers:
        - name: gateway
          image: quay.io/dmartin/mcp-gateway-poc
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
        - name: server1
          image: quay.io/dmartin/mcp-gateway-poc-server1
          ports:
            - containerPort: 8081
              protocol: TCP
          imagePullPolicy: Always
        - name: server2
          image: quay.io/dmartin/mcp-gateway-poc-server2
          ports:
            - containerPort: 8082
              protocol: TCP
          imagePullPolicy: Always


